class_name CollisionLayer

enum {
	WORLD_BODY = 1,
	PLAYER_BODY = 5,
	PLAYER_WEAPON = 6,
	ENEMY_BODY = 7,
	ENEMY_WEAPON = 8
}

enum {
	WORLD_BODY_MASK = 1<<(WORLD_BODY-1),
	PLAYER_BODY_MASK = 1<<(PLAYER_BODY-1),
	PLAYER_WEAPON_MASK = 1<<(PLAYER_WEAPON-1),
	ENEMY_BODY_MASK = 1<<(ENEMY_BODY-1),
	ENEMY_WEAPON_MASK = 1<<(ENEMY_WEAPON-1),
}